dependencies {
  implementation("androidx.appcompat:appcompat:1.7.0")
  implementation("com.google.android.material:material:1.12.0")
  implementation("androidx.constraintlayout:constraintlayout:2.2.0")
  implementation("androidx.fragment:fragment-ktx:1.8.5")
  implementation("androidx.recyclerview:recyclerview:1.3.2")
  implementation("androidx.viewpager2:viewpager2:1.1.0")

  implementation(platform(libs.androidx.compose.bom))
  implementation(platform(libs.firebase.bom))
  implementation(libs.androidx.activity.compose)
  implementation(libs.androidx.compose.material.icons.core)
  implementation(libs.androidx.compose.material.icons.extended)
  implementation(libs.androidx.compose.material3)
  implementation(libs.androidx.compose.ui)
  implementation(libs.androidx.compose.ui.graphics)
  implementation(libs.androidx.compose.ui.tooling.preview)
  implementation(libs.androidx.core.ktx)
  implementation(libs.androidx.lifecycle.runtime.compose)
  implementation(libs.androidx.lifecycle.runtime.ktx)
  implementation(libs.androidx.lifecycle.viewmodel.compose)
  implementation(libs.androidx.room.ktx)
  implementation(libs.androidx.room.runtime)
  implementation(libs.converter.moshi)
  implementation(libs.firebase.ai)
  
  // ✅ FIRESTORE
  implementation(libs.firebase.firestore)
  
  // ✅ FIREBASE STORAGE (For video clips)
  implementation("com.google.firebase:firebase-storage-ktx")
  
  // ✅ FIREBASE AUTH
  implementation("com.google.firebase:firebase-auth-ktx")
  
  // ✅ FIREBASE MESSAGING (For commands from laptop)
  implementation("com.google.firebase:firebase-messaging-ktx")

  implementation(libs.firebase.appcheck.recaptcha)
  implementation(libs.kotlinx.coroutines.android)
  implementation(libs.kotlinx.coroutines.core)
  implementation(libs.logging.interceptor)
  implementation(libs.moshi.kotlin)
  implementation(libs.okhttp)
  implementation(libs.retrofit)
  
  // ✅ GOOGLE DRIVE API
  implementation("com.google.api-client:google-api-client:2.2.0")
  implementation("com.google.oauth-client:google-oauth-client-jetty:1.34.1")
  implementation("com.google.apis:google-api-services-drive:v3-rev20220815-2.0.0")
  implementation("com.google.auth:google-auth-library-oauth2-http:1.19.0")

  // ❌ SUPABASE REMOVED
  // implementation(platform("io.github.jan-tennert.supabase:bom:3.5.0"))
  // implementation("io.github.jan-tennert.supabase:postgrest-kt")
  // implementation("io.github.jan-tennert.supabase:storage-kt")
  // implementation("io.github.jan-tennert.supabase:realtime-kt")
  // implementation("io.ktor:ktor-client-android:3.0.3")
  // implementation("io.ktor:ktor-client-content-negotiation:3.0.3")
  // implementation("io.ktor:ktor-serialization-kotlinx-json:3.0.3")
  // implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")

  testImplementation(libs.androidx.compose.ui.test.junit4)
  testImplementation(libs.androidx.core)
  testImplementation(libs.androidx.junit)
  testImplementation(libs.junit)
  testImplementation(libs.kotlinx.coroutines.test)
  testImplementation(libs.robolectric)
  testImplementation(libs.roborazzi)
  testImplementation(libs.roborazzi.compose)
  testImplementation(libs.roborazzi.junit.rule)
  androidTestImplementation(platform(libs.androidx.compose.bom))
  androidTestImplementation(libs.androidx.compose.ui.test.junit4)
  androidTestImplementation(libs.androidx.espresso.core)
  androidTestImplementation(libs.androidx.junit)
  androidTestImplementation(libs.androidx.runner)
  debugImplementation(libs.androidx.compose.ui.test.manifest)
  debugImplementation(libs.androidx.compose.ui.tooling)
  "ksp"(libs.androidx.room.compiler)
  "ksp"(libs.moshi.kotlin.codegen)
}
